[package]
name = "libp2p-bittorrent-protocol"
version = "0.1.0"
edition = "2018"
authors = ["matthiasseitz <matthias.seitz@tum.de>"]
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
futures = "0.1"
log = "0.4"
libp2p-core = "0.12.0"
libp2p-swarm = "0.2.0"
libp2p-kad = "0.2.0"
smallvec = "0.6"
bytes = "0.4"
tokio-codec = "0.1"
tokio-io = "0.1"
tokio-fs = "0.1"
rand = "0.6.0"
sha1 = "0.6.0"
sha2 = "0.8.0"
unsigned-varint = { version = "0.2.1", features = ["codec"] }
serde_bencode = { version = "^0.2.0", optional = true }
serde = { version = "^1.0.0", optional = true }
serde_derive = { version = "^1.0.0", optional = true }
wasm-timer = "0.1"
bendy = "0.2"
chrono = "0.4.9"
bitflags = "1.2.1"
bit-vec = "0.6.1"
snafu = "0.5.0"
byteorder = "1.3.2"
walkdir = "2.2.9"

[features]
bencode = ["serde_bencode", "serde", "serde_derive"]
